#

x-service: &service
  env_file: ".env"
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  front:
    << : *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver" ]
    dns: "${DNS:?}"
    networks: [ "default", "traefik_mailu" ]
    ports:
#      - "127.0.0.1:80:80"
      - "${IP4:?}:25:25"
      - "${IP4:?}:465:465"
      - "${IP4:?}:993:993"
#      - "[${IP6:?}]:25:25"
#      - "[${IP6:?}]:465:465"
#      - "[${IP6:?}]:993:993"
    volumes:
      - "./certs:/certs"
      - "./overrides/nginx:/overrides:ro"
      - "../letsencrypt:/etc/letsencrypt:ro"
    logging: { driver: "journald", options: { tag: "mailu-front" } }
    labels:
      - "traefik.docker.network=traefik_mailu"
      - "traefik.enable=true"
      - "traefik.http.routers.mailu.rule=HostRegexp(`mail.{host:.+}`) && PathPrefix(`/mailu`, `/sso`, `/static`)"
      - "traefik.http.routers.mailu.tls=true"
      - "traefik.http.services.mailu.loadbalancer.server.port=80"

  admin:
    << : *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "redis" ]
    dns: ${DNS:?}
    volumes:
      - "./data:/data"
      - "./dkim:/dkim"

  smtp:
    << : *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./mailqueue:/queue"
      - "./overrides/postfix:/overrides:ro"

  imap:
    << : *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./mail:/mail"
      - "./overrides/dovecot:/overrides:ro"

  antispam:
    << : *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "front", "redis" ]
    dns: "${DNS:?}"
    volumes:
      - "./filter:/var/lib/rspamd"
      - "./overrides/rspamd:/overrides:ro"

  redis:
    << : *service
    image: "redis:alpine"
    depends_on: [ "resolver" ]
    dns: "${DNS:?}"
    env_file: ""
    volumes:
      - "./redis:/data"

  resolver:
    << : *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}"
    networks: { default: { ipv4_address: "${DNS:?}" } }

networks:
  default:
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "${SUBNET:?}"
  traefik_mailu: { external: true }
