#

version: '3.9'

x-service:
  &service
  env_file: ".env"
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  front:
    << : *service
    image: "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:?}"
    depends_on: [ "resolver" ]
    dns: "${DNS:?}"
    ports:
      - "127.0.0.1:8180:80"
      - "${IP4:?}:25:25"
#      - "[${IP6:?}]:25:25"
      - "${IP4:?}:465:465"
#      - "[${IP6:?}]:465:465"
      - "${IP4:?}:587:587"
#      - "[${IP6:?}]:587:587"
      - "${IP4:?}:993:993"
#      - "[${IP6:?}]:993:993"
    volumes:
      - "./certs:/certs"
      - "./overrides/nginx:/overrides:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"

  admin:
    << : *service
    image: "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:?}"
    depends_on: [ "resolver", "redis" ]
    dns: ${DNS:?}
    volumes:
      - "./data:/data"
      - "./dkim:/dkim"

  smtp:
    << : *service
    image: "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:?}"
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./mailqueue:/queue"
      - "./overrides/postfix:/overrides:ro"

  imap:
    << : *service
    image: "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:?}"
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./mail:/mail"
      - "./overrides/dovecot:/overrides:ro"

  antispam:
    << : *service
    image: "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:?}"
    hostname: antispam
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./filter:/var/lib/rspamd"
      - "./overrides/rspamd:/etc/rspamd/override.d:ro"

  redis:
    << : *service
    image: "redis:alpine"
    depends_on: [ "resolver" ]
    dns: "${DNS:?}"
    volumes:
      - "./redis:/data"

  resolver:
    << : *service
    image: "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:?}"
    networks: { default: { ipv4_address: "${DNS:?}" } }

networks:
  default:
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "${SUBNET:?}"
