#

x-service: &service
  dns_search: .
  env_file: ".env"
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "15s"

services:

  front:
    <<: *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver" ]
    dns: "${DNS:?}"
    networks: [ "default", "traefik" ]
    ports:
#      - "127.0.0.1:80:80"
      - "${IP4:?}:25:25" # smtp
      - "${IP4:?}:465:465" # smtp tls
      - "${IP4:?}:587:587" # smtp starttls
      - "${IP4:?}:993:993" # imap tls
#      - "[${IP6:?}]:25:25"
#      - "[${IP6:?}]:465:465"
#      - "[${IP6:?}]:587:587"
#      - "[${IP6:?}]:993:993"
    volumes:
      - "./data/certs:/certs"
      - "../etc/letsencrypt/live/${DOMAIN:?}:/etc/letsencrypt/live/example.com:ro"
      - "./overrides/nginx:/overrides:ro"
    logging: { driver: "journald", options: { tag: "mailu-front" } }
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailu.middlewares=auth@file"
      - "traefik.http.routers.mailu.rule=HostRegexp(`^mail[.]`) && PathRegexp(`^/(mailu|sso|static)/`)"
      - "traefik.http.services.mailu.loadbalancer.server.port=80"

  admin:
    <<: *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "redis" ]
    dns: ${DNS:?}
    volumes:
      - "./data/admin:/data"
      - "./data/dkim:/dkim"

  smtp:
    <<: *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./data/smtp:/queue"
      - "./overrides/postfix:/overrides:ro"

  imap:
    <<: *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "front" ]
    dns: "${DNS:?}"
    volumes:
      - "./data/imap:/mail"
#      - "./overrides/dovecot:/overrides:ro"

  antispam:
    <<: *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}"
    depends_on: [ "resolver", "front", "redis" ]
    dns: "${DNS:?}"
    volumes:
      - "./data/rspamd:/var/lib/rspamd"
#      - "./overrides/rspamd:/overrides:ro"

  redis:
    <<: *service
    image: "redis:alpine"
    depends_on: [ "resolver" ]
    dns: "${DNS:?}"
    volumes:
      - "./data/redis:/data"

  resolver:
    <<: *service
    image: "${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}"
    networks: { default: { ipv4_address: "${DNS:?}" } }

networks:
  default: { ipam: { config: [ subnet: "${SUBNET:?}" ] } }
  traefik: { external: true }
