#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  cap_drop: [ "ALL" ]
  read_only: true
  security_opt: [ "no-new-privileges:true" ]

services:
  komga:
    << : *service
    image: "gotson/komga"
    environment:
      - "SERVER_SERVLET_CONTEXT_PATH=/komga/"
      - "KOMGA_REMEMBERME_KEY=${KOMGA_REMEMBERME_KEY:?}"
      - "KOMGA_REMEMBERME_VALIDITY=14d"
      - "KOMGA_SESSIONTIMEOUT=7d"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=PathRegexp(`^/komga($|/)`)"
      - "traefik.http.services.komga.loadbalancer.server.port=25600"
    networks: [ "traefik" ]
    tmpfs: [ "/tmp:mode=777,exec" ]
    user: "1000:1000"
    volumes:
      - "./.local/config:/config"
      - "./.local/data:/data"

networks:
  traefik: { external: true }
