#

version: '3.9'

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  komga:
    << : *service
    image: "gotson/komga"
    environment:
      - "SERVER_SERVLET_CONTEXT_PATH=/komga/"
      - "KOMGA_REMEMBERME_VALIDITY=14d"
      - "KOMGA_SESSIONTIMEOUT=7d"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=PathPrefix(`/komga`)"
      - "traefik.http.services.komga.loadbalancer.server.port=8080"
    networks: [ "traefik" ]
#    ports: [ "127.0.0.1:8080:8080" ]
    tmpfs: [ "/tmp:mode=777,exec" ]
    user: "1000:1000"
    volumes:
      - "./.cache/config:/config"
      - "./.cache/data:/data"

networks:
  traefik: { external: true }
