#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  cap_drop: [ "ALL", ]
  read_only: true
  security_opt: [ "no-new-privileges:true", ]

x-lsio: &lsio
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
#  cap_drop: [ "ALL", ]
#  read_only: true
  security_opt: [ "no-new-privileges:true", ]

services:

  qbittorrent:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile" }
    depends_on: [ "unbound", "socks", ]
    dns: "${SUBNET:?}.254"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.qbittorrent.stripprefix.prefixes=/qbittorrent"
      - "traefik.http.routers.qbittorrent.middlewares=authelia@docker,qbittorrent"
      - "traefik.http.routers.qbittorrent.rule=PathPrefix(`/qbittorrent`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    networks: [ "default", "traefik", ]
#    ports: [ "127.0.0.1:8080:8080", ]
    volumes:
      - "${HOME:?}/Downloads:/home/1000/Downloads"
      - "./.local/qbittorrent:/home/1000/.local/share/qBittorrent"
      - "./.local/qbittorrent:/home/1000/.config/qBittorrent"

  jackett:
    << : *lsio
    image: "lscr.io/linuxserver/jackett"
    depends_on: [ "unbound", "socks", ]
    dns: "${SUBNET:?}.254"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "AUTO_UPDATE=false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.middlewares=authelia@docker"
      - "traefik.http.routers.jackett.rule=PathPrefix(`/jackett`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
    networks:
      default: { aliases: [ "jackett_default" ] }
      inet:
      traefik:
#    ports: [ "127.0.0.1:9117:9117" ]
    volumes:
      - "./.local/jackett:/config"
      - "./.local/jackett:/downloads"

  sonarr:
    << : *lsio
    image: "lscr.io/linuxserver/sonarr"
    depends_on: [ "unbound", "socks", "sabnzbd", ]
    dns: "${SUBNET:?}.254"
    environment:
      - "PUID=1000"
      - "PGID=1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"
      - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks: [ "default", "inet", "traefik", ]
#    ports: [ "127.0.0.1:8989:8989" ]
    volumes:
      - "./.local/sonarr:/config"
      - "./.local/data:/data"

  sabnzbd:
    << : *lsio
    image: "lscr.io/linuxserver/sabnzbd"
    depends_on: [ "unbound", "socks", ]
    dns: "${SUBNET:?}.254"
    environment:
      - "PUID=1000"
      - "PGID=1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.middlewares=authelia@docker"
      - "traefik.http.routers.sabnzbd.rule=PathPrefix(`/sabnzbd`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
    networks:
      default: { aliases: [ "sabnzbd_default" ] }
      inet:
      traefik:
#    ports: [ "127.0.0.1:8080:8080" ]
    volumes:
      - "./.local/sabnzbd:/config"
      - "./.local/data:/data"

  socks:
    << : *service
    build: { context: ".", dockerfile: "../v2ray/Dockerfile" }
    depends_on: [ "unbound", ]
    dns: "${SUBNET:?}.254"
    environment:
      - "SOCKS_ADDRESS=${SOCKS_ADDRESS:?}"
      - "SOCKS_PASSWORD=${SOCKS_PASSWORD:?}"
      - "SOCKS_USER=${SOCKS_USER:?}"
    networks:
      default: { aliases: [ "socks_default" ] }
      inet:
    ports: [ "127.0.0.1:1080:1080", ]
    volumes:
      - "./v2ray.yml:/etc/v2ray/config.json:ro"

  unbound:
    << : *service
    build: { context: ".", dockerfile: "../doh/Dockerfile.unbound" }
    networks:
      default: { aliases: [ "unbound_default" ], ipv4_address: "${SUBNET:?}.254" }
      inet:
    volumes:
      - "../doh/unbound.conf:/etc/unbound/unbound.conf.d/unbound.conf:ro"

networks:
  default: { internal: true, ipam: { config: [ subnet: "${SUBNET:?}.0/24" ] } }
  inet: { external: true }
  traefik: { external: true }
