#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  # <https://github.com/gchq/CyberChef>
  cyberchef:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile", args: [ "TAG=v9.55.0" ] }
    networks: [ "traefik" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=PathPrefix(`/cyberchef/`)"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"

networks:
  traefik: { external: true }
