#

version: '3.9'

x-service:
  &service
  env_file: ".env"
  logging:
    { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  cyberchef:
    << : *service
    build: { context: ".", dockerfile: "Dockerfile", args: [ "TAG=v9.48.0" ] }
    networks: [ "default", "backend" ]
#    ports:
#      - "127.0.0.1:8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=PathPrefix(`/cyberchef`)"
      - "traefik.http.routers.cyberchef.tls=true"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=80"

networks:
  backend:
    external: true
