#

version: '3.9'

x-service:
  &service
  env_file: ".env"
  logging:
    { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  cyberchef:
    << : *service
    build: { context: ".", dockerfile: "Dockerfile", args: [ "TAG=${CYBERCHEF_TAG:?}" ] }
    ports:
      - "127.0.0.1:8080:80"
