#

version: "3.9"

x-service:
  &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  db:
    << : *service
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    volumes:
      - "db:/var/lib/postgresql/data"

  php:
    << : *service
    build: { context: ".", dockerfile: "Dockerfile.php" }
    command: "/run.sh"
    depends_on: [ "db" ]
    volumes:
      - "./run.sh:/run.sh:ro"
      - "./backup:/backup:rw"
      - ".cache/tt-rss:/var/www/html/tt-rss"

  tt-rss:
    << : *service
    image: "nginx:alpine"
    depends_on: [ "php" ]
    networks: [ "default", "backend" ]
#    ports:
#      - "127.0.0.1:80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - ".cache/tt-rss:/var/www/html/tt-rss"
    healthcheck:
      test: "curl --fail http://127.0.0.1/tt-rss/index.php || exit 1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tt-rss.loadbalancer.server.port=80"
      - "traefik.http.routers.tt-rss.rule=PathPrefix(`/tt-rss`)"

volumes:
  db:

networks:
  backend:
    external: true
