#

version: "3.9"

x-service:
  &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  db:
    << : *service
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    volumes:
      - "db:/var/lib/postgresql/data"

  rss:
    << : *service
    build: "."
    depends_on: [ "db" ]
    volumes:
      - "./backup:/var/run/tt-rss/backup:rw"
      - "rss:/var/www/html/tt-rss:rw"

  nginx:
    << : *service
    image: "nginx:alpine"
    depends_on: [ "rss" ]
    ports:
      - "127.0.0.1:9080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "rss:/var/www/html/tt-rss:ro"
    healthcheck:
      test: "curl --fail http://127.0.0.1/tt-rss/index.php || exit 1"

volumes:
  db:
  rss:
