#

version: "3.9"

x-service:
  &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  db:
    << : *service
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    volumes:
      - "db:/var/lib/postgresql/data"

  app:
    << : *service
    build: "."
    depends_on: [ "db" ]
    volumes:
      - "./backup:/var/run/tt-rss/backup:rw"
      - "tt-rss:/var/www/html/tt-rss:ro"

  web:
    << : *service
    image: "nginx:alpine"
    depends_on: [ "app" ]
    ports:
      - "127.0.0.1:9080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "tt-rss:/var/www/html/tt-rss:ro"

volumes:
  db:
  tt-rss:
