#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  matterircd:
    << : *service
    image: "42wim/matterircd"
    command: [
      "--bind", "0.0.0.0:6667",
      "--debug",
    ]
    ports: [ "127.0.0.1:6667:6667", ]
