#

version: "3.9"

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  elixir:
    << : *service
    build: { context: ".", dockerfile: "Dockerfile" }
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elixir.rule=PathPrefix(`/elixir`)"
      - "traefik.http.services.elixir.loadbalancer.server.port=8080"
    networks: [ "traefik" ]
    ports:
      - "127.0.0.1:8080:8080"
    tmpfs: [ "/tmp:mode=777" ]
    volumes:
      - "./.cache:/1000/proj_dir"
      - "./lighttpd.conf:/1000/lighttpd.conf:ro"

networks:
  traefik: { external: true }
