#

x-service: &service
  dns_search: .
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  cap_drop: [ "ALL" ]
  read_only: true
  security_opt: [ "no-new-privileges:true" ]
  user: "1000:1000"
  mem_limit: 256m

services:

  traefik:
    << : *service
    image: "traefik"
    command:
      - --accesslog=true
      - --api.dashboard=true
#      - --entrypoints.http.address=:80
#      - --entrypoints.http.http.redirections.entrypoint.to=https
#      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
#      - --entryPoints.https.forwardedHeaders.trustedIPs=127.0.0.0/8
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http3
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --log.level=WARN
#      - --ping
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://docker_sock:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
    depends_on: [ "docker_sock" ]
    environment:
      - "DOMAIN=${DOMAIN:?}"
      - "HOST=${HOST:?}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/authelia/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.routers.api.middlewares=auth@file"
      - "traefik.http.routers.api.rule=HostRegexp(`^traefik(-[0-9a-z]+)?[.]`) && PathPrefix(`/`)"
      - "traefik.http.routers.api.service=api@internal"
    networks: { "default", "inet", "traefik" : { ipv4_address: "${TRAEFIK_SUBNET:?}.254" } }
    ports:
#      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443/tcp"
      - "0.0.0.0:443:443/udp"
      - "[::]:443:443/tcp"
      - "[::]:443:443/udp"
    volumes:
      - "./traefik:/etc/traefik"
      - "../etc/letsencrypt/live:/etc/letsencrypt/live:ro"

  authelia:
    << : *service
    image: "authelia/authelia"
    environment:
      - "AUTHELIA_LOG_LEVEL=info"
      - "DOMAIN=${DOMAIN:?}"
      - "HOST=${HOST:?}"
      - "MACHINE_ID=${MACHINE_ID:?}"
      - "X_AUTHELIA_CONFIG_FILTERS=template"
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=HostRegexp(`^auth(-[0-9a-z]+)?[.]`) || PathRegexp(`^/authelia($|/)`)"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    volumes:
      - "./authelia:/config:rw"

  dozzle:
    << : *service
    image: "amir20/dozzle"
    depends_on: [ "docker_sock" ]
    environment:
      - "DOZZLE_BASE=/dozzle"
      - "DOZZLE_NO_ANALYTICS=true"
      - "DOZZLE_REMOTE_HOST=tcp://docker_sock:2375"
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.middlewares=auth@file"
      - "traefik.http.routers.dozzle.rule=PathPrefix(`/dozzle/`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

  docker_sock:
    << : *service
    image: "haproxy"
    group_add: [ "${DOCKER_GID:?}" ]
    #ports: [ "127.0.0.1:2375:2375", ]
    volumes:
      - "./haproxy.docker_sock.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default: { internal: true }
  inet: { external: true }
  traefik: { external: true }
