#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  traefik:
    << : *service
    image: "traefik:latest"
    command:
      - --accesslog=true
      - --api.dashboard=true
#      - --entrypoints.http.address=:80
#      - --entrypoints.http.http.redirections.entrypoint.to=https
#      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
#      - --entryPoints.https.forwardedHeaders.trustedIPs=127.0.0.1/32,192.168.0.1/16
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --log.level=WARN
#      - --ping
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://docker_sock:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
    depends_on: [ "docker_sock", ]
    environment:
      - "DOMAIN=${DOMAIN:?}"
    labels:
      - "traefik.enable=true"
#      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/authelia/api/verify?rd=https://${DOMAIN:?}/authelia/#/"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/authelia/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.routers.api.middlewares=auth@file"
      - "traefik.http.routers.api.rule=HostRegexp(`traefik.{host:.+}`)"
      - "traefik.http.routers.api.service=api@internal"
    networks: { "default", "inet", "traefik" : { ipv4_address: 172.31.255.254 } }
    ports:
#      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "./traefik:/etc/traefik"
      - "../etc/letsencrypt/live:/etc/letsencrypt/live:ro"

  authelia:
    << : *service
    image: "authelia/authelia"
    environment:
      - "AUTHELIA_LOG_LEVEL=debug"
      - "AUTHELIA_SERVER_DISABLE_HEALTHCHECK=true"
      - "AUTHELIA_SERVER_PATH=authelia"
      - "AUTHELIA_SESSION_DOMAIN=${DOMAIN}"
      - "AUTHELIA_JWT_SECRET_FILE=/config/jwt_secret.key"
      - "AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/storage_encryption_key.key"
      - "AUTHELIA_SESSION_SECRET_FILE=/config/session_secret.key"
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=PathPrefix(`/authelia`)"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    user: "1000:1000"
    volumes:
      - "./authelia:/config:rw"

  docker_sock:
    << : *service
    image: "tecnativa/docker-socket-proxy"
    environment:
      - "CONTAINERS=1"
#    ports: [ "127.0.0.1:2375:2375", ]
    tmpfs: [ "/run", ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dozzle:
    << : *service
    image: "amir20/dozzle"
    depends_on: [ "docker_sock", ]
    environment:
      - "DOZZLE_BASE=/dozzle"
      - "DOZZLE_NO_ANALYTICS=true"
      - "DOCKER_HOST=tcp://docker_sock:2375"
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.middlewares=authelia@docker"
      - "traefik.http.routers.dozzle.rule=PathPrefix(`/dozzle`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
#    ports: [ "127.0.0.1:8080:8080", ]
#    profiles: [ "TEST", ]
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default: { internal: true }
  inet:
  traefik: { external: true }
