#

version: "3.9"

x-service:
  &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  traefik:
    << : *service
    image: "traefik:latest"
    command:
      - --accesslog=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --log.level=WARN
      - --ping
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=backend
      - --providers.file.directory=/etc/traefik
    healthcheck:
      test: "traefik healthcheck --ping || exit 1"
    networks: [ "default", "backend" ]
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
#      - "0.0.0.0:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"
      - "./letsencrypt/live:/etc/letsencrypt/live:ro"

  nginx:
    << : *service
    image: "nginx:alpine"
    healthcheck:
      test: "curl --fail http://127.0.0.1/index.html || exit 1"
#    ports:
#      - "0.0.0.0:80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf.d:/etc/nginx/templates:ro"
      - "/opt/html:/opt/html:ro"
      - "socat:/run/socat:rw"
      - "./letsencrypt/live:/etc/letsencrypt/live:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  socat:
    << : *service
    build: "../socat"
    command:
      - "/etc/socat/run.sh"
      - "syncthing:127.0.0.1:8384"
    network_mode: "host"
    volumes:
      - "socat:/run/socat:rw"
      - "../socat:/etc/socat:ro"

  whoami:
    << : *service
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

volumes:
  socat:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  backend:
    external: true
