#

version: "3.9"

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  traefik:
    << : *service
    image: "traefik:latest"
    command:
      - --accesslog=true
      - --api.dashboard=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --log.level=WARN
      - --ping
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://docker_sock:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.file.directory=/etc/traefik
    depends_on: [ "docker_sock" ]
    environment:
      - "DOMAIN=${DOMAIN:?}"
    healthcheck:
      test: "traefik healthcheck --ping || exit 1"
    labels:
      - "traefik.enable=true"
#      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/authelia/api/verify?rd=https://${DOMAIN:?}/authelia/#/"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/authelia/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.routers.api.middlewares=auth@file"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN:?}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
    networks: [ "default", "traefik", "traefik_jenkins", "traefik_jupyter", "traefik_mailu", "traefik_portainer", "traefik_upkuma" ]
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
#      - "127.0.0.1:8080:8080"
    volumes:
      - "./traefik:/etc/traefik"
      - "../letsencrypt/live:/etc/letsencrypt/live:ro"

  authelia:
    << : *service
    image: "authelia/authelia"
    environment:
      - "AUTHELIA_LOG_LEVEL=debug"
      - "AUTHELIA_SERVER_DISABLE_HEALTHCHECK=true"
      - "AUTHELIA_SERVER_PATH=authelia"
      - "AUTHELIA_SESSION_DOMAIN=${DOMAIN}"
      - "AUTHELIA_JWT_SECRET_FILE=/config/jwt_secret.key"
      - "AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/storage_encryption_key.key"
      - "AUTHELIA_SESSION_SECRET_FILE=/config/session_secret.key"
    labels:
      - "traefik.docker.network=traefik_default"
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=PathPrefix(`/authelia`)"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
    user: "1000:1000"
    volumes:
      - "./authelia:/config:rw"

  docker_sock:
    << : *service
    image: "tecnativa/docker-socket-proxy"
    environment:
      - "CONTAINERS=1"
    tmpfs: [ "/run" ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
  traefik: { external: true }
  traefik_jenkins: { external: true }
  traefik_jupyter: { external: true }
  traefik_mailu: { external: true }
  traefik_portainer: { external: true }
  traefik_upkuma: { external: true }
