#

version: "3.9"

x-service:
  &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  traefik:
    << : *service
    image: "traefik:latest"
    command:
      - --accesslog=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=backend
      - --providers.file.filename=/etc/traefik/provider.yml
    networks: [ "default", "backend" ]
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"
#      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/etc/letsencrypt/archive:/etc/letsencrypt/archive:ro"
      - "/etc/letsencrypt/live/${DOMAIN:?}:/etc/letsencrypt/live/example.com:ro"

  nginx:
    << : *service
    image: "nginx:alpine"
#    ports:
#      - "0.0.0.0:80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf.d:/etc/nginx/templates:ro"
      - "/opt/html:/opt/html:ro"
      - "socat:/run/socat:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  socat:
    << : *service
    build: "./socat"
    command: >
      /etc/socat/run.sh
      syncthing:127.0.0.1:8384
    network_mode: "host"
    volumes:
      - "socat:/run/socat:rw"
      - ./socat:/etc/socat:ro

volumes:
  socat:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  backend:
    external: true
