#

api:
  dashboard: true
  insecure: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    http:
      tls: true

log:
  level: DEBUG

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik-tls.yml"
