#

FROM archlinux:latest

RUN pacman -Sy && pacman -S --noconfirm \
    git make \
    libxcrypt-compat \
    && pacman -Sc --noconfirm

WORKDIR /home/1000
RUN chown 1000:1000 .
USER 1000:1000
ENV HOME="/home/1000"

RUN git clone https://github.com/akozlins/dotfiles .dotfiles
RUN ln -s .dotfiles/.profile
RUN ln -s .dotfiles/.bashrc

RUN git clone https://github.com/akozlins/vhdutil
