#

FROM archlinux:latest

RUN echo "[multilib]" >> /etc/pacman.conf \
 && echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

RUN pacman -Sy
RUN pacman -S --noconfirm \
    cmake gcc diffutils git make nano openssh \
    libxcrypt-compat

WORKDIR /root

RUN git clone https://github.com/akozlins/dotfiles .dotfiles
RUN ln -s .dotfiles/.profile

RUN git clone https://github.com/akozlins/vhdutil
