#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  user: "1000:1000"

services:

  grafana:
    <<: *service
    image: "grafana/grafana-oss"
    environment:
      #- "GF_AUTH_ANONYMOUS_ENABLED=true"
      #- "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_BASIC_ENABLED=false"
      - "GF_AUTH_PROXY_ENABLED=true"
      - "GF_AUTH_PROXY_HEADER_NAME=Remote-User"
      - "GF_AUTH_PROXY_WHITELIST=${TRAEFIK_SUBNET:?}.0/24"
      - "GF_SERVER_ROOT_URL=/grafana"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.middlewares=auth@file"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana/`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks: [ "default", "traefik" ]
    volumes:
      - "./.local/grafana:/var/lib/grafana"

  prometheus:
    <<: *service
    image: "prom/prometheus"
    command: >
      "--config.file=/prometheus.yml"
      "--web.listen-address=0.0.0.0:9090"
      "--web.route-prefix=/prometheus"
      "--web.enable-admin-api"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.middlewares=auth@file"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus/`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks: [ "default", "inet", "traefik" ]
    volumes:
      - "./prometheus.yml:/prometheus.yml"
      - "./.local/prometheus:/prometheus"

networks:
  default: { internal: true }
  inet: { external: true }
  traefik: { external: true }
