#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  user: "1000:1000"

services:

  grafana:
    <<: *service
    image: "grafana/grafana-oss"
    environment:
      #- "GF_AUTH_ANONYMOUS_ENABLED=true"
      #- "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_BASIC_ENABLED=false"
      - "GF_AUTH_PROXY_ENABLED=true"
      - "GF_AUTH_PROXY_HEADER_NAME=Remote-User"
      #- "GF_AUTH_PROXY_HEADERS=Name:Remote-User Role:X-WEBAUTH-ROLE Email:Remote-Email Groups:Remote-Groups"
      - "GF_AUTH_PROXY_WHITELIST=${TRAEFIK_SUBNET:?}.0/24"
      - "GF_SERVER_ROOT_URL=/grafana"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.middlewares=auth@file"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana/`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks: [ "default", "traefik" ]
    volumes:
      - "./.local/grafana:/var/lib/grafana"

  # <https://hub.docker.com/r/victoriametrics/victoria-metrics>
  victoria:
    <<: *service
    image: "victoriametrics/victoria-metrics:latest"
    command: >
      "-http.pathPrefix=/victoria"
      "-storageDataPath=/victoria"
      "-retentionPeriod=99y"
      "-selfScrapeInterval=5s"
      "-promscrape.config=/scrape.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.victoria.middlewares=auth@file"
      - "traefik.http.routers.victoria.rule=PathPrefix(`/victoria/`)"
      - "traefik.http.services.victoria.loadbalancer.server.port=8428"
    networks: [ "default", "inet", "traefik" ]
    volumes:
      - "./scrape.yaml:/scrape.yaml"
      - "./.local/victoria:/victoria"

networks:
  default: { internal: true }
  inet: { external: true }
  traefik: { external: true }
