#

global:
  scrape_interval: 15s

scrape_configs:

- job_name: test1
  scheme: http
  metrics_path: /metrics
  static_configs:
  - targets: [ 10.0.0.1:9100 ]

- job_name: test2
  scheme: https
  basic_auth:
    username: user
    password: pass
  metrics_path: /prometheus/node-exporter
  static_configs:
  - targets: [ example.com ]
