#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  cap_drop: [ "ALL" ]
  read_only: true
  security_opt: [ "no-new-privileges:true" ]
  user: "1000:1000"
  mem_limit: 64m

services:

  gpt:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile" }
    cap_add: [ "CAP_NET_BIND_SERVICE" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gpt.stripprefix.prefixes=/gpt"
      - "traefik.http.routers.gpt.middlewares=auth@file,gpt"
      - "traefik.http.routers.gpt.rule=PathPrefix(`/gpt/`)"
      - "traefik.http.services.gpt.loadbalancer.server.port=80"
    networks: [ "traefik" ]

networks:
  inet: { external: true }
  traefik: { external: true }
