#

FROM debian

RUN apt-get update && apt-get --yes --no-install-recommends install \
    dumb-init ca-certificates unbound \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /etc/unbound

USER 1000:1000

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "unbound", "-d" ]
