#

FROM alpine

RUN apk add --no-cache \
    bind-tools dumb-init gettext openssl unbound

WORKDIR /etc/unbound

RUN echo 'include: "/etc/unbound/conf.d/*.conf"' >> unbound.conf

USER 1000:1000

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "unbound", "-d" ]
