version: '3'

services:

  unbound:
    build:
      context:
        ./unbound
    volumes:
      - "./unbound/unbound.conf:/etc/unbound/conf.d/unbound.conf:ro"
    logging:
      options:
        max-size: 1m

  proxy:
    build:
      context: dns-over-https
    volumes:
      - "./dns-over-https/doh-server.conf:/doh-server.conf:ro"
    ports:
      - 127.0.0.1:8053:8053
    depends_on:
      - unbound
    logging:
      options:
        max-size: 1m
