#

FROM debian

RUN apt-get update && apt-get --yes --no-install-recommends install \
    ca-certificates dumb-init entr gettext unbound \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /etc/unbound

USER 1000:1000

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
#CMD [ "unbound", "-d", "-p" ]
CMD echo unbound.conf | entr -nrz bash -c "exec unbound -d -p -c <(envsubst < unbound.conf)"
