#

FROM golang:alpine AS build

WORKDIR /src

RUN apk add --no-cache \
    git make

RUN git clone https://github.com/m13253/dns-over-https .
RUN make doh-server/doh-server

#

FROM alpine

EXPOSE 8053

RUN apk add --no-cache \
    dumb-init

COPY --from=build /src/doh-server/doh-server /doh-server

USER 1000

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/doh-server", "-conf", "/doh-server.conf" ]
