#

version: "3.9"

x-service: &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  postgres:
    << : *service
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    volumes:
      - "postgres:/var/lib/postgresql/data"

  php:
    << : *service
    build: { context: ".", dockerfile: "Dockerfile.php" }
    command: "/run.sh"
    depends_on: [ "postgres" ]
    environment:
      - TTRSS_DB_HOST=postgres
      - TTRSS_DB_NAME=db
      - TTRSS_DB_PASS=password
      - TTRSS_DB_USER=user
      - TTRSS_PHP_EXECUTABLE=/usr/bin/php8
      - TTRSS_PLUGINS=auth_internal
      - TTRSS_SELF_URL_PATH=/tt-rss
      # default lifetime of a session cookie in seconds
      # (0 means cookie will be deleted when browser closes)
      - TTRSS_SESSION_COOKIE_LIFETIME=31415927
    volumes:
      - "./run.sh:/run.sh:ro"
      - "./backup:/backup:rw"
      - "./.cache/tt-rss:/var/www/html/tt-rss"

  nginx:
    << : *service
    image: "nginx:alpine"
    depends_on: [ "php" ]
    healthcheck:
      test: "curl --fail http://127.0.0.1/tt-rss/index.php || exit 1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tt-rss.rule=PathPrefix(`/tt-rss`)"
      - "traefik.http.routers.tt-rss.tls=true"
      - "traefik.http.services.tt-rss.loadbalancer.server.port=80"
    networks: [ "default", "backend" ]
#    ports:
#      - "127.0.0.1:80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.cache/tt-rss:/var/www/html/tt-rss"


volumes:
  postgres:

networks:
  backend:
    external: true
