#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  searx:
    << : *service
    image: "searxng/searxng"
    environment:
      - "BASE_URL=/searx/"
      - "SEARXNG_BASE_URL=/searx/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searx.middlewares=authelia@docker"
      - "traefik.http.routers.searx.rule=PathPrefix(`/searx`)"
      - "traefik.http.services.searx.loadbalancer.server.port=8080"
    networks: [ "inet", "traefik", ]
#    ports: [ "127.0.0.1:8080:8080", ]
    volumes:
      - "./.local:/etc/searxng"

networks:
  inet: { external: true }
  traefik: { external: true }
