#

version: "3.9"

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  searx:
    << : *service
    image: "searxng/searxng"
    environment:
      - "BASE_URL=/searx/"
      - "SEARXNG_BASE_URL=/searx/"
    healthcheck:
      test: "wget -q --spider http://127.0.0.1:8080/searx/ || exit 1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searx.middlewares=auth@file"
      - "traefik.http.routers.searx.rule=PathPrefix(`/searx`)"
      - "traefik.http.routers.searx.tls=true"
      - "traefik.http.services.searx.loadbalancer.server.port=8080"
    networks: [ "traefik" ]
#    ports:
#      - "127.0.0.1:8080:8080"
    volumes:
      - ".cache:/etc/searx"
      - ".cache:/etc/searxng"
      - "uwsgi:/var/log/uwsgi:rw"

volumes:
  uwsgi:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  traefik: { external: true }
