#

http:
  middlewares:
    auth_users:
      basicauth:
        # `htpasswd -nb -B username password | cut -d ":" -f 2`
        usersFile: "/etc/traefik/users.key"
    auth_rlimit:
      ratelimit:
        average: 25
        burst: 200
        period: 1s
    auth:
      chain:
        middlewares: [ "auth_rlimit", "authelia@docker", "security_headers" ]
    security_headers:
      headers:
        browserXssFilter: true
        contentSecurityPolicy: "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'self';"
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "no-referrer"
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

  {{ $routers := dict "test" "10.8.0.1" }}
  routers:
    {{ range $k, $v := $routers }}
    {{$k}}-router:
      priority: 255
      rule: "HostRegexp(`^([0-9a-z]+-)?{{$k}}[.]`)"
      service: "{{$k}}-service"
      tls: true
    {{end}}
  serversTransports:
    default-transport:
      serverName: '{{env "DOMAIN"}}'
  services:
    {{ range $k, $v := $routers }}
    {{$k}}-service:
      loadBalancer:
        servers: [ url: "https://{{$v}}" ]
        serversTransport: "default-transport"
    {{end}}
