#

http:
  middlewares:
    auth_users:
      basicauth:
        # `htpasswd -nb -B username password | cut -d ":" -f 2`
        usersFile: "/etc/traefik/users.key"
    auth_rlimit:
      ratelimit:
        average: 25
        burst: 50
        period: 1s
    auth:
      chain:
        middlewares: [ "auth_rlimit", "authelia_rd@docker", "security_headers" ]
    security_headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "no-referrer"
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

  routers:
    test-router:
      rule: "Host(`test.{{env "DOMAIN"}}`)"
      service: "test-service"
      tls: true
  serversTransports:
    default-transport:
      serverName: '{{env "DOMAIN"}}'
  services:
    test-service:
      loadBalancer:
        servers: [ url: "https://10.8.0.1" ]
        serversTransport: "default-transport"
