#

http:
  middlewares:
    auth:
      basicauth:
        # `htpasswd -nb -B username password | cut -d ":" -f 2`
        usersFile: "/etc/traefik/users.key"

  routers:
    test-router:
      rule: "Host(`test.{{env "DOMAIN"}}`)"
      service: "test-service"
      tls: true
  serversTransports:
    default-transport: { serverName: "{{env "DOMAIN"}}" }
  services:
    test-service:
      loadBalancer:
        servers: [ url: "https://10.8.0.1", ]
        serversTransport: "default-transport"
