#

tcp:
  routers:
    ssh-router:
      rule: "HostSNIRegexp(`ssh.{host:.+}`)"
      service: "ssh-service"
      tls: true
    vpn-router:
      rule: "HostSNIRegexp(`vpn.{host:.+}`)"
      service: "vpn-service"
      tls: true
  services:
    ssh-service:
      loadBalancer: { servers: [ address: "{{env "DOMAIN"}}:22", ] }
    vpn-service:
      loadBalancer: { servers: [ address: "{{env "DOMAIN"}}:1194", ] }
