#

{{define "port-router"}}
    p{{.}}:
      rule: "HostSNIRegexp(`^p{{.}}[.]`)"
      service: "p{{.}}"
      tls: true
{{end}}
{{define "port-service"}}
    p{{.}}:
      loadBalancer: { servers: [ address: "{{env "DOMAIN"}}:{{.}}" ] }
{{end}}

tcp:
  routers:
    {{template "port-router" 1022}}
    ssh-router:
      rule: "HostSNIRegexp(`^ssh[.]`)"
      service: "ssh-service"
      tls: true
    vpn-router:
      rule: "HostSNIRegexp(`^vpn[.]`)"
      service: "vpn-service"
      tls: true
    #test-router:
    #  rule: "HostSNIRegexp(`^test[.]`)"
    #  service: "test-service"
    #  tls: { passthrough: true }
  services:
    {{template "port-service" 1022}}
    ssh-service:
      loadBalancer: { servers: [ address: "{{env "DOMAIN"}}:22" ] }
    vpn-service:
      loadBalancer: { servers: [ address: "{{env "DOMAIN"}}:1194" ] }
