#

version: "3"

services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./templates:/etc/nginx/templates:ro"
      - "./logs:/etc/nginx/logs:rw"
      - "/opt/html:/opt/html:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
#      - "/etc/letsencrypt/live/${DOMAIN:?}:/etc/letsencrypt/live/example.com"
      - "socat:/run/socat:rw"
    environment:
      - "DOMAIN=${DOMAIN:?}"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:8443"
    depends_on:
      - "socat"
#    restart: "unless-stopped"
    stop_grace_period: 5s
    logging:
      options:
        max-size: 1m

  # create unix sockets that redirect to 127.0.0.1:$port on host network
  socat:
    image: "alpine:edge"
    volumes:
      - "socat:/run/socat:rw"
      - ./socat:/etc/socat:ro
    command: sh -c "set -euf
        && ( test -x /usr/bin/socat || apk --no-cache add socat )
        && exec /etc/socat/run.sh 1022 8008 8180 8280 8380"
    network_mode: "host"

volumes:
  socat:
