#

version: "3.9"

x-service:
  &service
  env_file: .env
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  nginx:
    << : *service
    image: "nginx:alpine"
#    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:8443"
      - "[::]:80:80"
      - "[::]:443:8443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./conf.d:/etc/nginx/templates:ro"
      - "./logs:/etc/nginx/logs:rw"
      - "/opt/html:/opt/html:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
#      - "./${DOMAIN:?}:/etc/letsencrypt/live/${DOMAIN:?}:ro"
      - "socat:/run/socat:rw"
    healthcheck:
      test: "curl --fail http://127.0.0.1:80 || exit 1"

  # create unix sockets that redirect to 127.0.0.1:$port on host network
  socat:
    << : *service
    image: "alpine"
    command: sh -c "set -euf
        && ( test -x /usr/bin/bash || apk --no-cache add bash )
        && ( test -x /usr/bin/socat || apk --no-cache add socat )
        && exec /etc/socat/run.sh 1022 1443 2580 8008 8053 8080 9080"
    network_mode: "host"
    volumes:
      - "socat:/run/socat:rw"
      - ./socat:/etc/socat:ro

  sslh:
    << : *service
    build: "./sslh"
    command: --listen=127.0.0.1:1443 --ssh=127.0.0.1:22 --openvpn=127.0.0.1:1194 --anyprot=127.0.0.1:1194 --on-timeout=anyprot
    network_mode: "host"

volumes:
  socat:
    driver_opts:
      type: tmpfs
      device: tmpfs
