#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  nginx:
    << : *service
    image: "nginx"
    environment:
      - "DOMAIN=${DOMAIN:?}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.priority=1"
      - "traefik.http.routers.nginx1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.nginx.rule=HostRegexp(`nginx.{host:.+}`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"
    networks: [ "default", "traefik", ]
#    ports: [ "0.0.0.0:8080:8080", ]
    tmpfs: [ "/tmp:mode=777", ]
    volumes:
      - "./conf.d:/etc/nginx/templates:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../etc/letsencrypt:/etc/letsencrypt:ro"
      - "./.cache/opt/html:/opt/html:ro"
      - "./.cache/run/socat:/run/socat:rw"

  socat:
    << : *service
    build: "./socat"
    command:
      - "/etc/socat/run.sh"
      - "syncthing.sock:127.0.0.1:8384"
    network_mode: "host"
    volumes:
      - "./socat:/etc/socat:ro"
      - "./.cache/run/socat:/run/socat:rw"

  sslh:
    << : *service
    build: "./sslh"
    command: [ "sslh", "--foreground", "--numeric",
      "--listen=0.0.0.0:80",
      "--anyprot=nginx:80",
      "--openvpn=${DOMAIN:?}:1194",
      "--ssh=${DOMAIN:?}:22",
      "--on-timeout=anyprot",
    ]
    depends_on: [ "nginx", ]
    networks: [ "default", "inet", ]
    ports: [ "0.0.0.0:80:80", ]

  whoami:
    << : *service
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.middlewares=authelia@docker"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks: [ "default", "traefik", ]

networks:
  default: { internal: true }
  inet:  { external: true }
  traefik: { external: true }
