#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
#  cap_drop: [ "ALL", ]
#  read_only: true
  security_opt: [ "no-new-privileges:true", ]

services:
  jenkins:
    << : *service
    image: "jenkins/jenkins"
    environment:
      - "JAVA_OPTS=-Xmx1g"
      - "JENKINS_OPTS=--prefix=/jenkins"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.middlewares=authelia@docker"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins/`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks: [ "inet", "traefik", ]
#    ports: [ "127.0.0.1:8080:8080", ]
    tmpfs: [ "/tmp:mode=777,exec", ]
    volumes:
      - "./.cache/jenkins:/var/jenkins_home"

  node0:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile.node" }
    networks: [ "inet", ]
    volumes:
      - "./.cache/node:/home/jenkins"
    profiles: [ "NODE", ]

networks:
  inet:
  traefik: { external: true }
