#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  jenkins:
    << : *service
    image: "jenkins/jenkins:lts-jdk11"
    environment:
      - "JENKINS_OPTS=--prefix=/jenkins"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.middlewares=authelia@docker"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks: [ "default", "traefik", ]
#    ports: [ "127.0.0.1:8080:8080", ]
    tmpfs: [ "/tmp:mode=777,exec", ]
    volumes:
      - "./.cache/jenkins_home:/var/jenkins_home"

  jenkins-node:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile.node" }
    profiles: [ "TEST", ]
    volumes:
      - "./.cache/node:/home/jenkins"

networks:
  default:
  traefik: { external: true }
