#

version: "3.9"

x-service:
  &service
  env_file: ".env"
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  jenkins:
    << : *service
    image: "jenkins/jenkins:lts-jdk11"
#    ports:
#      - "127.0.0.1:8080:8080"
#      - "127.0.0.1:50000:50000"
    volumes:
      - "workspace:/var/jenkins_home"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)"

volumes:
  workspace:

networks:
  default:
    name: nginx-network
    external: true
