#

FROM archlinux

RUN pacman -Sy
RUN pacman -S --noconfirm \
    cmake gcc git make openssh

# jenkins node
RUN pacman -S --noconfirm \
    jre11-openjdk

# cleanup
RUN pacman -Scc --noconfirm

RUN groupadd --gid 1000 jenkins && \
    useradd --gid 1000 --uid 1000 -m jenkins

USER root
# generate sshd keys
RUN ssh-keygen -A
# start sshd
CMD (/usr/bin/sshd -D -e) || (/usr/sbin/sshd -D -e)
