#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  php:
    << : *service
    build: { context: ".", dockerfile: "../rss_tt/Dockerfile.php" }
    command: [ "/run.sh", ]
    environment:
      - "FRESHRSS_BASE_URL=https://${DOMAIN:?}/fresh"
    networks: [ "default", "inet", ]
    volumes:
      - "./run.sh:/run.sh:ro"
      - "./.local:/var/www"

  nginx:
    << : *service
    image: "nginx:alpine"
    depends_on: [ "php", ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fresh_nginx.middlewares=authelia@docker"
      - "traefik.http.routers.fresh_nginx.rule=PathPrefix(`/fresh`)"
      - "traefik.http.services.fresh_nginx.loadbalancer.server.port=8080"
    networks: [ "default", "traefik", ]
#    ports:[ "127.0.0.1:8080:8080", ]
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.local:/var/www"

networks:
  default: { internal: true }
  inet: { external: true }
  traefik: { external: true }
