#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  openvpn:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile" }
    cap_add:
      - "NET_ADMIN"
    devices:
      - "/dev/net/tun"
    networks: [ "inet", "traefik" ]
#    ports: [ "127.0.0.1:1194:1194" ]
    tmpfs: [ "/tmp" ]
    volumes:
      - "./.cache:/run/openvpn:rw"
      - "./server.conf:/etc/openvpn/config.conf:ro"
      - "../etc/easy-rsa/openvpn/server.key:/etc/openvpn/server.key:ro"
      - "../etc/easy-rsa/openvpn/server.crt:/etc/openvpn/server.crt:ro"
      - "../etc/easy-rsa/pki/ca.crt:/etc/openvpn/ca.crt:ro"
      - "../etc/easy-rsa/pki/dh.pem:/etc/openvpn/dh.pem:ro"
      - "../etc/easy-rsa/pki/ta.key:/etc/openvpn/ta.key:ro"

networks:
  inet: { external: true }
  traefik: { external: true }
