#

version: '3.9'

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  openvpn:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile" }
    cap_add:
      - "NET_ADMIN"
    devices:
      - "/dev/net/tun"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.openvpn.rule=HostSNI(`vpn.${DOMAIN:?}`)"
      - "traefik.tcp.routers.openvpn.tls=true"
      - "traefik.tcp.services.openvpn.loadbalancer.server.port=1194"
    networks: [ "traefik" ]
    ports:
      - "127.0.0.1:1194:1194"
    volumes:
      - "./server:/etc/openvpn/server:rw"
      - "./.cache:/run/openvpn:rw"

networks:
  traefik: { external: true }
