#

# <https://www.authelia.com/integration/prologue/get-started/>
# <https://www.authelia.com/configuration/miscellaneous/introduction/>

authentication_backend:
  password_reset:
    disable: true
  # <https://www.authelia.com/configuration/first-factor/file/>
  file:
    path: "/config/users.yml"
    watch: true
    search:
      email: true

server:
  address: "tcp://:9091/authelia"
  disable_healthcheck: true

# <https://www.authelia.com/configuration/storage/introduction/>
storage:
  encryption_key: '{{ secret "/config/storage_encryption_key.key" }}'
  local:
    path: "/config/.cache/storage.sqlite3"

# <https://www.authelia.com/configuration/session/introduction/>
session:
  cookies:
  - domain: '{{ env "DOMAIN" }}'
    authelia_url: 'https://{{ env "DOMAIN" }}/authelia'
  secret: '{{ secret "/config/session_secret.key" }}'

notifier:
  filesystem:
    filename: "/config/notifier.txt"

access_control:
  default_policy: "deny"
  rules:
    - domain_regex: ".*"
      policy: "one_factor"
