#

# <https://www.authelia.com/integration/prologue/get-started/>
# <https://www.authelia.com/configuration/miscellaneous/introduction/>

authentication_backend:
  password_reset:
    disable: true
  # <https://www.authelia.com/configuration/first-factor/file/>
  file:
    path: "/config/users.yml"
    watch: true
    search:
      email: true

server:
  address: "tcp://:9091/authelia"
  disable_healthcheck: true

# <https://www.authelia.com/configuration/storage/introduction/>
storage:
  encryption_key: '{{ secret "/config/storage_encryption_key.key" }}'
  local:
    path: "/config/.cache/storage.sqlite3"

# <https://www.authelia.com/configuration/session/introduction/>
session:
  cookies:
  - domain: '{{ env "DOMAIN" }}'
    authelia_url: 'https://{{ env "DOMAIN" }}/authelia'
    name: 'authelia_session_{{ env "HOST" }}'
  secret: '{{ secret "/config/session_secret.key" }}'

notifier:
  filesystem:
    filename: "/config/.cache/notifier.txt"

access_control:
  default_policy: "deny"
  rules:
    - domain_regex: ".*"
      policy: "one_factor"
      subject: [ "group:admin" ]

identity_providers:
  oidc:
    hmac_secret: '{{ secret "/config/oidc_hmac_secret.key" }}'
    jwks:
      # `openssl req -x509 -nodes -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -subj "/CN=$DOMAIN"`
      - key: {{ secret "/config/oidc_jwks_key.key" | mindent 10 "|" | msquote }}
    clients:
      - {{ fileContent "/config/oidc_client_example.yml" | nindent 8 }}
