#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  upkuma:
    << : *service
#    image: "louislam/uptime-kuma"
    build: { context: ".", dockerfile: "Dockerfile", }
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "UPTIME_KUMA_BASE_PATH=/upkuma/"
    labels:
      - "traefik.docker.network=traefik_upkuma"
      - "traefik.enable=true"
      - "traefik.http.routers.upkuma.middlewares=authelia@docker"
      - "traefik.http.routers.upkuma.rule=PathPrefix(`/upkuma`)"
      - "traefik.http.services.upkuma.loadbalancer.server.port=3001"
    networks: [ "traefik_upkuma" ]
#    ports: [ "127.0.0.1:3001:3001" ]
    volumes:
      - "./.cache:/app/data"

networks:
  traefik_upkuma: { external: true }
