#

include ../makefile.mk

init ::
	mkdir -p -- .local/outline .local/postgres .local/redis
	#docker-compose run --rm outline yarn db:create --env=production-ssl-disabled
	#docker-compose run --rm outline yarn db:migrate --env=production-ssl-disabled
