#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  coder:
    << : *service
#    image: codercom/code-server
    build: { context: ".", dockerfile: "./Dockerfile" }
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.coder.stripprefix.prefixes=/coder"
      - "traefik.http.routers.coder.middlewares=authelia@docker,coder"
      - "traefik.http.routers.coder.rule=PathPrefix(`/coder`)"
      - "traefik.http.services.coder.loadbalancer.server.port=8080"
    networks: [ "inet", "traefik", ]
#    ports: [ "127.0.0.1:8080:8080", ]
    tmpfs: [ "/tmp:mode=777,exec", ]
    user: "1000:1000"
    volumes:
      - ./.cache:/home/coder

networks:
  inet:
  traefik: { external: true }
