#

x-service: &service
  dns_search: .
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:
  coder:
    <<: *service
    #image: "codercom/code-server"
    image: "akozlins/coder"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.coder.stripprefix.prefixes=/coder"
      - "traefik.http.routers.coder.middlewares=auth@file,coder"
      - "traefik.http.routers.coder.rule=PathPrefix(`/coder/`)"
      - "traefik.http.services.coder.loadbalancer.server.port=8080"
    networks: [ "inet", "traefik" ]
    user: "1000:1000"
    volumes:
      - ./home:/home/coder

networks:
  inet: { external: true }
  traefik: { external: true }
