#

x-service:
  &service
  cap_drop: [ "ALL" ]
  logging: { options: { max-size: "1m" } }
  read_only: true
  restart: "always"
  security_opt: [ "no-new-privileges:true" ]
  stop_grace_period: "5s"

services:

  flask:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile" }
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=PathPrefix(`/telegram`)"
      - "traefik.http.services.flask.loadbalancer.server.port=8080"
    networks: [ "traefik" ]
    volumes:
      - "./:/home/1000/:ro"

networks:
  traefik: { external: true }
