#

x-service:
  &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"
  cap_drop: [ "ALL", ]
  read_only: true
  security_opt: [ "no-new-privileges:true", ]

services:

  flask:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile" }
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=PathPrefix(`/telegram`)"
      - "traefik.http.services.flask.loadbalancer.server.port=8080"
    networks: [ "inet", "traefik", ]
    volumes:
      - "./:/home/1000/:ro"

networks:
  inet: { external: true }
  traefik: { external: true }
