#

x-service: &service
  logging: { options: { max-size: "1m" } }
  restart: "always"
  stop_grace_period: "5s"

services:

  rss_db:
    << : *service
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
      - POSTGRES_USER=${DB_USER:?}
    healthcheck:
      test: "/backup/backup.sh || exit 1"
      interval: 30s
      start_period: 30s
    networks: [ "default", ]
    volumes:
      - "db:/var/lib/postgresql/data"
      - "./backup:/backup:rw"

  rss_php:
    << : *service
    build: { context: ".", dockerfile: "./Dockerfile.php" }
    command: [ "/run.sh", ]
    depends_on: [ "rss_db", ]
    environment:
      - TTRSS_DB_HOST=rss_db
      - TTRSS_DB_NAME=db_name
      - TTRSS_DB_PASS=${DB_PASSWORD:?}
      - TTRSS_DB_USER=${DB_USER:?}
      - TTRSS_PHP_EXECUTABLE=/usr/bin/php8
      - TTRSS_PLUGINS=auth_internal
      - TTRSS_SELF_URL_PATH=/rss
      # default lifetime of a session cookie in seconds
      # (0 means cookie will be deleted when browser closes)
      - TTRSS_SESSION_COOKIE_LIFETIME=31415927
    networks: [ "default", "inet", ]
    volumes:
      - "./run.sh:/run.sh:ro"
      - "./.cache/tt-rss:/var/www/html/rss"

  rss:
    << : *service
    image: "nginx:alpine"
    depends_on: [ "rss_php", ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss.rule=PathPrefix(`/rss`)"
      - "traefik.http.services.rss.loadbalancer.server.port=80"
    networks: [ "default", "traefik", ]
#    ports:[ "127.0.0.1:80:80", ]
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.cache/tt-rss:/var/www/html/rss"

volumes:
  db:

networks:
  default: { internal: true }
  inet:
  traefik: { external: true }
